FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ai_5g_load_balancing/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ai_5g_load_balancing /app

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
